const ordersTypes = {
  SAVE_ORDER_HISTORY_START: "SAVE_ORDER_HISTORY_START",
  GET_USER_ORDER_HISTORY_START: "GET_USER_ORDER_HISTORY_START",
  SET_USER_ORDER_HISTORY: "SET_USER_ORDER_HISTORY",
  GET_ORDER_DETAILS_START: "GET_ORDER_DETAILS_START",
  SET_ORDER_DETAILS: "SET_ORDER_DETAILS",
  GET_ALL_ORDERS: "GET_ALL_ORDERS",
  SET_ALL_ORDERS: "SET_ALL_ORDERS",
  UPDATE_ORDER_STATUS: "UPDATE_ORDER_STATUS",
  SET_ORDERS_NOTIFICATION_DATA: "SET_ORDERS_NOTIFICATION_DATA",
  SET_ORDER_TOTAL: "SET_ORDER_TOTAL",
  GET_LATEST_ORDERS: "GET_LATEST_ORDERS",
  SET_LATEST_ORDERS: "SET_LATEST_ORDERS",
  GET_ORDERS_STATS: "GET_ORDERS_STATS",
  SET_ORDERS_STATS: "SET_ORDERS_STATS",
  GET_WEEKLY_ORDERS: "GET_WEEKLY_ORDERS",
  SET_WEEKLY_ORDERS: "SET_WEEKLY_ORDERS",
  DELETE_ORDER: "DELETE_ORDER",
};

export default ordersTypes;
