const productsTypes = {
  ADD_NEW_PRODUCT_START: "ADD_NEW_PRODUCT_START",
  FETCH_PRODUCTS_START: "FETCH_PRODUCTS_START",
  SET_PRODUCTS: "SET_PRODUCTS",
  DELETE_PRODUCTS_START: " DELETE_PRODUCTS_START",
  FETCH_PRODUCT_START: "FETCH_PRODUCT_START",
  SET_PRODUCT: "SET_PRODUCT",
  UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
  ADD_PRODUCT_REVIEW_START: "ADD_PRODUCT_REVIEW_START",
  FETCH_PRODUCT_REVIEW_START: "FETCH_PRODUCT_REVIEW_START",
  SET_PRODUCT_REVIEW: "SET_PRODUCT_REVIEW",
};

export default productsTypes;
