const userTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GET_ALL_USERS: "GET_ALL_USERS",
  SET_ALL_USERS: "SET_ALL_USERS",
  GET_TOTAL_USERS: "GET_TOTAL_USERS",
  SET_TOTAL_USERS: "SET_TOTAL_USERS", 
};

export default userTypes;
